FROM golang:1.10 AS builder

ADD https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep
ENV TOKEN = "c3dc1555c0cc8debd17ea5b8a1240baa0abd93c5"
WORKDIR $GOPATH/src/github.com/phil192/rediq
ADD . ./$WORKDIR
COPY Gopkg.toml Gopkg.lock ./
RUN dep ensure --vendor-only

RUN CGO_ENABLED=0 GOOS=linux go build -i

CMD ./rediq
EXPOSE 8081