FROM golang:1.10 AS builder

ADD https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep

WORKDIR $GOPATH/src/github.com/phil192/rediq
ADD . ./$WORKDIR
COPY Gopkg.toml Gopkg.lock ./
RUN dep ensure --vendor-only

RUN CGO_ENABLED=0 GOOS=linux go build -i cmd/client/main.go

CMD ./main
EXPOSE 8081